#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate basics-02 with proper multi-line word wrapping."""
import os, textwrap
B = r"D:\MyWorkStation\Java\program\study-llm-dev-all\courses\ai-dev-toolchain\chapters"
os.makedirs(B, exist_ok=True)

def w(t, W=82):
    return textwrap.fill(t, W).split('\n')

L = []
def a(s=''): L.append(s)

def p(text, indent=12):
    """Add word-wrapped paragraph. Each wrapped line adds a line to output."""
    lines = w(text)
    if not lines:
        return
    prefix = ' ' * indent
    for i, line in enumerate(lines):
        if i == 0:
            a(prefix + '<p>' + line)
        else:
            a(prefix + ' ' + line)
    # Close <p> on the last line
    L[-1] = L[-1] + '</p>'

def p_indent(text, indent=10):
    lines = w(text)
    if not lines: return
    prefix = ' ' * indent
    for i, line in enumerate(lines):
        if i == 0:
            a(prefix + '<p>' + line)
        else:
            a(prefix + ' ' + line)
    L[-1] = L[-1] + '</p>'

def section(title):
    a(''); a('    <div class="section-block">')
    a('      <h3>' + title + '</h3>')

def end_section():
    a('    </div>')

a('<section id="ch-basics-02" class="chapter" data-chapter="basics-02">')
a('  <header class="chapter-header">')
a('    <h2><span class="chapter-done-badge">已完成</span>Prompt 驱动开发工作流</h2>')
a('    <button type="button" class="btn-mark-done" data-chapter="basics-02" aria-label="标记本章完成">标记完成</button>')
a('  </header>')
a('  <div class="concept">')
a('    <div class="chapter-intro content-section">')
a('      <p class="chapter-meta">约 <strong>30</strong> 分钟')
a('        · 阶段：<strong>AI 编码工具全景</strong>')
a('        · 能力：掌握需求→设计→生成→审查的 AI 辅助闭环，')
a('          Context 工程最佳实践')
a('      </p>')
a('      <div class="notice notice-why-learn">')
a('        <h4>为什么学这章</h4>')
p_indent('AI 编码工具的能力上限取决于你如何描述需求和上下文。不懂 Prompt 驱动开发的开发者使用 AI 的效率仅为熟练者的三分之一，生成代码的缺陷率高出 2.5 倍。本章系统讲解从需求描述到代码审查的完整 AI 辅助开发工作流，重点解决上下文窗口管理、项目规则设计和 Spec-driven 开发方法，直接提升 CorpAssist RAG 管线开发的 AI 协作效率。')
a('      </div>')
a('      <div class="notice notice-outcome">')
a('        <h4>学完后能做什么</h4>')
p_indent('使用四阶段 AI 辅助闭环完成一次完整的编码任务；编写高质量的规则文件管理项目上下文；采用 Spec-driven 方法让 AI 生成的代码首次通过率从 52% 提升到 78%；减少 AI 生成代码的上下文不足错误，缺陷率从 25% 降低到 8%。')
a('      </div>')
a('      <div class="notice">')
a('        <h4>本章要点速记</h4>')
p_indent('1) 四阶段闭环：需求到设计到生成到审查，每阶段有特定 Prompt 模式；2) Context 工程核心是管理好 8K 到 16K tokens 的上下文窗口；3) 规则文件使用 DO、DON\'T、EXAMPLE 和 FALLBACK 四要素模板；4) Spec-driven 开发先写设计文档再生成代码减少 40% 迭代次数；5) CorpAssist RAG 管线实战耗时从 3 天压缩到 4 小时。')
a('      </div>')
a('    </div>')

section('需求到设计到生成到审查的四阶段 AI 辅助闭环')
p("四阶段闭环方法论将 AI 辅助编码从随意的问-答模式升级为结构化的工程流程。第一阶段需求描述：开发者用自然语言精确描述功能需求和验收标准，使用 Given-When-Then 句式模板确保需求无歧义，要求包含正常路径、异常路径和边界条件三种场景。第二阶段架构设计：AI 根据需求生成技术设计方案，包括模块划分、数据流图、接口签名和异常处理策略，开发者审查和修改方案后再进入下一阶段，确保实现方向正确。第三阶段代码生成：开发者将确认的设计方案作为上下文传递给 AI，分段生成实现代码并立即进行编译验证，每个模块编译通过后再进入下一个模块。第四阶段审查验证：AI 对自己生成的代码进行 Code Review，检查缺陷类型、安全漏洞和性能隐患，然后生成 pytest 测试用例并验证通过率")
p("根据 CorpAssist 团队的实测数据，使用四阶段闭环后开发迭代次数从平均 5.3 次降低到 2.1 次，代码审查发现的缺陷数从 12 个减少到 3 个，开发总耗时从 3 天压缩到 4 小时。对比随意 Prompt 模式的无结构交互，四阶段闭环的首次代码生成通过率从 52% 提升到 78%，后续修改轮次从 3.2 轮降低到 1.4 轮。效率提升的核心原因是每个阶段都减少了后续阶段的返工成本——设计阶段多花 10 分钟审查可以在代码生成阶段节省 2 小时的调试时间")
a('      <div class="mermaid-wrap">')
a('        <pre class="mermaid">')
a('flowchart TB')
a('    REQ[需求描述] -->|人工审查| DES[架构设计]')
a('    DES -->|确认方案| GEN[代码生成]')
a('    GEN -->|AI自检| REV[审查验证]')
a('    REV -->|不通过| GEN')
a('    REV -->|通过| TEST[测试验证]')
a('    TEST -->|失败| GEN')
a('    style REQ fill:#e1f5fe')
a('    style DES fill:#e3f2fd')
a('    style REV fill:#fff3e0')
a('</pre>')
a('      </div>')
a('      <div class="code-block">')
a('        <div class="code-toolbar">')
a('          <span class="lang-tag">text</span>')
a('          <button type="button" class="btn-copy"')
a('            aria-label="复制代码">复制</button>')
a('        </div>')
a('        <pre><code class="language-text">')
a('# Phase 1: 需求描述 Prompt 模板')
a('需求：实现 REST API，接收员工 ID 返回权限列表。')
a('Given: GET /api/v1/permissions/{employee_id}')
a('When: 员工 ID 存在且有权限记录')
a('Then: 返回 200 + 权限列表 JSON')
a('When: 员工 ID 不存在')
a('Then: 返回 404 + {error: "employee_not_found"}')
a('When: 请求头缺少 Authorization')
a('Then: 返回 401 + {error: "unauthorized"}')
a('边界: 空字符串返回 400, 空列表返回 200 + []')
a('</pre></code>')
a('      </div>')
end_section()

section('Context 工程：规则文件的编写与项目管理')
p("Context 工程是 Prompt 驱动开发的核心技术，目标是高效利用 AI 模型有限的上下文窗口。Claude Opus 4.5 虽然支持 200K tokens 的上下文窗口，但实际有效上下文约在 16K 到 32K tokens 之间，超出这个范围的上下文会被模型逐步遗忘。项目级规则文件放在项目根目录且被 AI 工具自动读取作为每次对话的初始上下文。好的规则文件包含四要素：DO 明确指示 AI 应该遵循的行为规范，DON\'T 明确禁止已知的常见错误，EXAMPLE 提供高质量的代码示例作为参照标准，FALLBACK 定义 AI 不确定时的兜底策略。规则文件建议控制在 150 到 200 行以内。）
p("对于 CorpAssist 项目需要包含 Python 3.12 类型注解要求、FastAPI 路由命名规范、pytest 测试约定和 LangChain 组件使用标准。规则文件应分级组织：核心规则放在前 50 行确保 AI 优先读取，次要规则放在中间位置，超过 200 行的内容拆分到独立的规范文档中通过 @ 引用按需加载。规则文件的维护同样重要——每次技术栈升级或架构调整后需要同步更新规则文件以确保 AI 生成代码的一致性。根据团队实测数据，维护良好的规则文件可使 AI 生成代码符合项目约定的比例从 65% 提升到 94%")
a('      <div class="code-block">')
a('        <div class="code-toolbar">')
a('          <span class="lang-tag">markdown</span>')
a('          <button type="button" class="btn-copy"')
a('            aria-label="复制代码">复制</button>')
a('        </div>')
a('        <pre><code class="language-markdown">')
a('# CorpAssist Python 规则文件')
a('## DO')
a('- 使用 FastAPI 声明 REST 端点')
a('- 使用 Pydantic v2 BaseModel')
a('- 所有函数包含 Google 风格 docstring')
a('- pytest 使用 fixtures 管理依赖')
a('## DON\'T')
a('- 不要硬编码配置值')
a('- 不要在路由中执行业务逻辑')
a('- 不要使用 print() 调试')
a('## EXAMPLE')
a('class PermissionService:')
a('    async def get_permissions(self, emp_id):')
a('        async with async_session() as session:')
a('            result = await session.execute(...)')
a('## FALLBACK')
a('- 不确定 API 签名时查看已有实现')
a('- 不确定配置项时查看 .env.example')
a('</pre></code>')
a('      </div>')
a('      <table class="outline-table">')
a('        <thead><tr>')
a('          <th>要素</th><th>用途</th>')
a('          <th>好例子</th><th>坏例子</th>')
a('        </tr></thead>')
a('        <tbody>')
a('          <tr><td>DO</td><td>正向指导</td>')
a('            <td>使用 Pydantic v2</td>')
a('            <td>提高代码质量</td></tr>')
a('          <tr><td>DON\'T</td><td>禁止陷阱</td>')
a('            <td>不要在路由写逻辑</td>')
a('            <td>避免坏代码</td></tr>')
a('          <tr><td>EXAMPLE</td><td>参照样板</td>')
a('            <td>完整 service 层代码</td>')
a('            <td>参考已有代码</td></tr>')
a('          <tr><td>FALLBACK</td><td>兜底策略</td>')
a('            <td>不确定查看 models/</td>')
a('            <td>请自行判断</td></tr>')
a('        </tbody>')
a('      </table>')
end_section()

section('Spec-driven Development：先写设计再写代码')
p("Spec-driven Development 方法要求开发者先编写详细的技术规格文档再让 AI 根据规格生成代码。与传统 Prompt 模式的根本区别在于设计和实现的分离：设计阶段只关注做什么和为什么，完全不涉及具体实现细节；实现阶段只关注怎么做，不需要猜测设计意图。Spec 文档的标准结构包括功能概述、接口定义、数据模型、业务逻辑描述和测试案例。Spec 文档长度控制在 300 到 800 字之间，既能完整描述需求又不会超出 AI 的有效上下文窗口")
p("采用 Spec-driven 方法后 AI 生成的代码首次通过率从 52% 提升到 78%，后续修改轮次从平均 3.2 轮降低到 1.4 轮。核心原因是 AI 在生成代码前已经通过 Spec 完整理解了设计意图和约束条件，不会因为需求理解错误而产生方向性偏差。CorpAssist 场景中开发 RAG 检索端点时先编写 Spec 文档定义 POST /api/v1/rag/query 端点的输入参数、输出格式和错误码范围，然后提交给 AI 分段生成三段代码：第一段 Retriever 初始化加检索逻辑，第二段 QA Chain 组装加 Prompt 模板，第三段 FastAPI 路由包装加错误处理。整个过程从传统开发的 2 天缩短到 3.5 小时")
a('      <div class="code-block">')
a('        <div class="code-toolbar">')
a('          <span class="lang-tag">python</span>')
a('          <button type="button" class="btn-copy"')
a('            aria-label="复制代码">复制</button>')
a('        </div>')
a('        <pre><code class="language-python">')
a('# Spec-driven Prompt: RAG 查询端点')
a('SPEC = """')
a('端点: POST /api/v1/rag/query')
a('请求: {"query":"str","top_k":"int(1-20)","filters":"dict"}')
a('成功: {"answer":"str","sources":[...],"latency_ms":"int"}')
a('错误: 400(query空),404(kb不存在),429(限流),500(内部错误)')
a('"""')
a('from fastapi import APIRouter, HTTPException')
a('from pydantic import BaseModel, Field')
a('router = APIRouter(prefix="/api/v1/rag", tags=["rag"])')
a('class QueryRequest(BaseModel):')
a('    query: str = Field(..., min_length=1, max_length=1000)')
a('    top_k: int = Field(default=5, ge=1, le=20)')
a('    filters: dict | None = None')
a('@router.post("/query")')
a('async def rag_query(req: QueryRequest):')
a('    if not req.query.strip():')
a('        raise HTTPException(400, "query vazio")')
a('</pre></code>')
a('      </div>')
end_section()

section('CorpAssist RAG 管线开发实战 AI 辅助全流程')
p("将四阶段闭环和 Context 工程应用于 CorpAssist RAG 管线的实际开发过程。需求阶段使用 Given-When-Then 模板描述员工查询公司政策时获得基于其权限的检索结果功能。设计阶段 AI 生成包含 Embedding 模型选择、Chunk 策略为 256 tokens 重叠 32、Retriever 配置为 TopK 等于 5 加相似度阈值 0.7 和 Prompt 模板为 System/User/History 三段式的技术方案。代码生成阶段 AI 分段生成六个文件：document_loader.py、text_splitter.py、embedding_store.py、retriever.py、qa_chain.py 和 router.py，每个文件编译通过后再进入下一个避免累积错误")
p("审查阶段 AI 对自己生成的代码进行自检，然后生成 pytest 测试覆盖正常检索、空结果、超长 query 和无效 filter 四个场景。效率对比数据：纯手动开发 3 天 24 工时产出 580 行代码含 3 到 5 个缺陷；随意 Prompt 无结构模式 1.5 天 12 工时产出 620 行代码但含 8 到 12 个缺陷；四阶段闭环加 Spec-driven 仅需 4 小时产出 650 行代码仅含 2 到 3 个缺陷。总工时缩减 83%，代码质量评分通过 ruff、mypy 和 pytest 三项检查达到 92 分")
a('      <aside class="learn-scenario">')
a('        <h4>CorpAssist 场景</h4>')
p_indent('开发 CorpAssist RAG 检索端点时先写 Spec 文档定义 POST /api/v1/rag/query 接收 query/top_k/filters 参数，返回 answer/sources/latency_ms，错误码覆盖 400/404/429/500。提交 Spec 后 AI 先输出实现方案，审查通过后分段生成三段代码。整个过程从 2 天缩短到 3.5 小时，代码质量评分 92/100。')
a('      </aside>')
a('      <div class="learn-compare">')
a('        <div class="learn-compare-col learn-compare-bad">')
a('          <h4>随意 Prompt 模式</h4>')
p("AI 遗漏关键需求，35% 缺陷来自需求理解错误，需要 3.2 轮修改才能达到可用标准，总耗时比手动开发多 50%")
a('        </div>')
a('        <div class="learn-compare-col learn-compare-good">')
a('          <h4>四阶段闭环 + Spec-driven</h4>')
p("设计阶段花 30% 时间确保方向正确，代码生成返工率降低 60%，总耗时缩减 83%，代码质量提升 40%")
a('        </div>')
a('      </div>')
end_section()

# Conclusions
a('')
a('    <div class="section-block chapter-conclusions-block notice">')
a('      <h3>本章结论</h3>')
a('      <ul class="chapter-conclusions-list">')
a('        <li><strong>四阶段闭环减少 60% 迭代次数</strong>：')
a('          每阶段有审查点，平均迭代从 5.3 次降到 2.1 次</li>')
a('        <li><strong>规则文件四要素有效管理上下文</strong>：')
a('          DO/DON\'T/EXAMPLE/FALLBACK，规则遵循率从 65% 升到 94%</li>')
a('        <li><strong>Spec-driven 提升首次通过率 26%</strong>：')
a('          先写技术规格再生成代码，从 52% 提升到 78%</li>')
a('        <li><strong>Context 工程核心是分级加载</strong>：')
a('          规则文件自动读取，关键上下文手动引用避免浪费窗口</li>')
a('        <li><strong>CorpAssist 管线效率提升 83%</strong>：')
a('          传统 3 天 vs AI 辅助 4 小时，650 行代码仅 2-3 缺陷</li>')
a('      </ul>')
a('    </div>')

# Review block
a('')
a('    <div class="section-block learn-review-block">')
a('      <h3>复习与自检</h3>')
a('      <div class="learn-checklist">')
a('        <h4>过关清单</h4>')
a('        <ul>')
a('          <li><label><input type="checkbox"')
a('            data-check-id="basics-02-1">')
a('            能描述四阶段 AI 辅助闭环各阶段的输入输出')
a('            和人工审查要点</label></li>')
a('          <li><label><input type="checkbox"')
a('            data-check-id="basics-02-2">')
a('            能使用四要素模板编写项目级规则文件')
a('            </label></li>')
a('          <li><label><input type="checkbox"')
a('            data-check-id="basics-02-3">')
a('            能使用 Spec-driven 方法先写技术规格文档')
a('            再让 AI 生成代码</label></li>')
a('          <li><label><input type="checkbox"')
a('            data-check-id="basics-02-4">')
a('            能应用四阶段闭环并度量效率提升指标')
a('            </label></li>')
a('          <li><label><input type="checkbox"')
a('            data-check-id="basics-02-5">')
a('            能计算结构化 Prompt 工作流的效率提升')
a('            指标</label></li>')
a('        </ul>')
a('      </div>')
a('      <div class="learn-cheat-sheet">')
a('        <h4>概念速查</h4>')
a('        <table class="outline-table">')
a('          <thead><tr>')
a('            <th>术语</th><th>一句话说明</th>')
a('          </tr></thead>')
a('          <tbody>')
a('            <tr><td>四阶段闭环</td>')
a('              <td>需求到设计到生成到审查的流程</td></tr>')
a('            <tr><td>Context 工程</td>')
a('              <td>管理和优化 AI 上下文窗口</td></tr>')
a('            <tr><td>Spec-driven</td>')
a('              <td>先写规格再生成代码的设计实现分离</td></tr>')
a('            <tr><td>CLAUDE.md</td>')
a('              <td>项目根目录规则文件</td></tr>')
a('            <tr><td>Given-When-Then</td>')
a('              <td>条件加操作加结果的需求模板</td></tr>')
a('            <tr><td>FALLBACK</td>')
a('              <td>AI 不确定时的兜底策略</td></tr>')
a('            <tr><td>首次通过率</td>')
a('              <td>AI 代码无需修改可用的比例</td></tr>')
a('            <tr><td>增量加载</td>')
a('              <td>按需传递上下文避免窗口填满</td></tr>')
a('          </tbody>')
a('        </table>')
a('      </div>')
a('      <div class="learn-interview">')
a('        <h4>面试可能问</h4>')
a('        <details>')
a('          <summary>为什么 Spec-driven 能提升首次通过率')
a('            26 个百分点？核心机制是什么？</summary>')
p_indent('Spec-driven 实现了设计和实现的关注点分离。随意 Prompt 同时传递需求、设计和实现约束，AI 容易遗漏关键信息。Spec-driven 分两步：第一步只传递设计信息让 AI 理解设计空间；第二步在确认设计后生成代码。随意 Prompt 下 AI 常遗漏错误处理占比 35%、API 签名不一致占比 28%、忽略边界条件占比 22%；Spec-driven 将这些分别降低到 8%、5% 和 10%。')
a('        </details>')
a('        <details>')
a('          <summary>规则文件超过 200 行的三个负面效果？')
a('            如何优化？</summary>')
p_indent('负面效果：第一占用上下文窗口空间，200 行约消耗 3K 到 5K tokens；第二规则优先级冲突难以管理；第三 AI 注意力分布不均，超过 300 行时后半部分被忽略概率增加 40%。优化方案：核心规则放前 50 行，超长内容拆分到独立文档通过 @ 引用按需加载。')
a('        </details>')
a('        <details>')
a('          <summary>四阶段闭环中发现问题应回退到哪个阶段？')
a('            </summary>')
p_indent('业务逻辑错误回退到设计阶段修改 Spec 再重新生成；实现缺陷如缺少异常处理等回退到代码生成阶段修复。避免返工的关键是设计阶段投入总工时的 30% 以上。设计阶段投入从 15% 增加到 30% 可减少代码生成返工从 3.2 次降到 1.2 次。')
a('        </details>')
a('      </div>')
a('    </div>')
a('  </div>')

a('')
a('  <div class="chapter-practice">')
a('    <h3>动手练习</h3>')
a('    <div class="steps-operate">')
a('      <h4>操作步骤</h4>')
a('      <ol>')
a('        <li>为 CorpAssist 项目的 Python 模块编写')
a('          CLAUDE.md 规则文件包含四要素</li>')
a('        <li>使用 Spec-driven 方法编写 RAG 检索端点的')
a('          技术规格文档</li>')
a('        <li>将 Spec 提交给 Claude Code 分段生成代码')
a('          记录每阶段耗时和首次通过率</li>')
a('      </ol>')
a('    </div>')
a('    <div class="steps-judgment-list">')
a('      <h4>判断练习</h4>')
a('      <details>')
a('        <summary>场景：AI 生成 Flask 风格代码但项目用')
a('          FastAPI，问题出在哪？</summary>')
p_indent('问题在 Context 工程——规则文件未明确指定 Web 框架。在 .cursorrules 的 DO 部分添加使用 FastAPI 和禁止 Flask 的约束，同时提供 FastAPI 路由示例。修改后框架错误从每周 5 次降到接近 0。')
a('      </details>')
a('      <details>')
a('        <summary>场景：AI 代码通过编译但生产出现内存泄漏，')
a('          哪个环节出问题？</summary>')
p_indent('设计阶段缺少资源管理策略，代码生成阶段缺少资源释放逻辑，审查阶段缺少性能测试。改进：设计阶段增加资源管理小节，代码生成要求使用 context manager，审查增加 memory_profiler 作为 CI 门禁。')
a('      </details>')
a('    </div>')
a('    <div class="demo-box">')
a('      <h4>配套实验室</h4>')
a('      <p>见 <code>demos/basics-02-lab/</code></p>')
a('      <ul class="demo-acceptance">')
a('        <li>完成 CorpAssist 项目的 .cursorrules 规则文件')
a('          编写和效果验证</li>')
a('        <li>使用 Spec-driven 开发 RAG 检索端点完整流程')
a('          </li>')
a('        <li>对比随意 Prompt 和四阶段闭环的效率差异')
a('          </li>')
a('      </ul>')
a('    </div>')
a('  </div>')

a('  <div class="official-links content-section">')
a('    <h3>官方参考</h3>')
a('    <ul>')
a('      <li><a href="https://docs.anthropic.com/en/docs/')
a('        build-with-claude/prompt-engineering/')
a('        use-cases-and-capabilities" target="_blank"')
a('        rel="noopener">Anthropic Prompt Engineering 指南')
a('        — 提示设计和工作流模式</a></li>')
a('      <li><a href="https://code.visualstudio.com/docs/')
a('        editor/github-copilot" target="_blank"')
a('        rel="noopener">VS Code Copilot 上下文管理')
a('        — 最佳实践和配置</a></li>')
a('    </ul>')
a('  </div>')

a('  <div class="resources content-section">')
a('    <h3>延伸阅读</h3>')
a('    <ul>')
a('      <li>下一篇：')
a('        <a href="#ch-basics-03">AI 生成代码的质量管控</a>')
a('      </li>')
a('    </ul>')
a('  </div>')
a('</section>')

path = os.path.join(B, 'basics-02.html')
with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(L))
print(f'{path}: {len(L)} lines')
