server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-actuator-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/actuator/**
              filters:
                - StripPrefix=2
            - id: inventory-actuator-route
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/actuator/**
              filters:
                - StripPrefix=2
            - id: order-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=1
            - id: inventory-route
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**
              filters:
                - StripPrefix=1
